---
- name: Fetch list of current teams
  uri: 
    url: "{{ sysdig_api_endpoint }}/api/teams"
    method: GET
    headers:
        Authorization: "Bearer {{ sysdig_token }}"
        Content-Type: "application/json"
  register: teams_output
- name: Fetch list of current users
  uri: 
    url: "{{ sysdig_api_endpoint }}/api/users"
    method: GET
    headers:
        Authorization: "Bearer {{ sysdig_token }}"
        Content-Type: "application/json"
  register: users_output

- name: Write users output to file
  copy:
    content: "{{ users_output | to_nice_json }}"
    dest: "/tmp/users_output.json"

- name: Write teams output to file
  copy:
    content: "{{ teams_output | to_nice_json }}"
    dest: "/tmp/teams_output.json"

