---
# Lookup Team
- debug: msg=" Looking up team - {{ container_team_name }}"

- set_fact: 
    container_team_data: "{{ item }}"
    container_team_exists: true
  when: item.name == container_team_name
  with_items: 
    -  "{{ teams_output.json.teams }}"
  no_log: true

# Create Team if Doesn't Exist
- name: Create container-scoped team
  uri: 
    url: "{{ sysdig_api_endpoint }}/api/teams"
    method: POST
    headers:
        Authorization: "Bearer {{ sysdig_token }}"
        Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/new_container_team.json.j2') }}"
    body_format: json
    status_code: 201
  register: team_container_creation_output
  when: container_team_exists == false

# Update Team if Exists Updates
- name: Update Container Scoped Team
  uri: 
    url: "{{ sysdig_api_endpoint }}/api/teams/{{ container_team_data.id | int }}"
    method: PUT
    headers:
        Authorization: "Bearer {{ sysdig_token }}"
        Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/existing_container_team.json.j2') }}"
    body_format: json
    status_code: 200
  register: team_container_update_output
  when: container_team_exists == true
