---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.devops.gov.bc.ca
  resources:
  - sysdig-team-go
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.devops.gov.bc.ca
  resources:
  - sysdig-team-go/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.devops.gov.bc.ca
  resources:
  - sysdig-team-go/status
  verbs:
  - get
  - patch
  - update
