# permissions for end users to edit sysdig-teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sysdig-operator
    app.kubernetes.io/managed-by: kustomize
  name: sysdigteams-editor-role
rules:
- apiGroups:
  - monitoring.devops.gov.bc.ca
  resources:
  - sysdig-teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.devops.gov.bc.ca
  resources:
  - sysdig-teams/status
  verbs:
  - get 
