# prep: jmespath
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files: 
    - vars/vars-sample.yaml
  tasks:
    - name: get all alerts
      include_tasks: tasks/get_all_alerts.yaml

    # - name: Get a dashboard
    #   include_tasks: tasks/alerts.yaml
    #   with_items: 
    #     - "{{ target_alert_ids }}"
    #   loop_control: 
    #     loop_var: alert_id

    - name: get all dashboards
      include_tasks: tasks/get_all_dashboards.yaml

    # - name: Get a dashboard
    #   include_tasks: tasks/dashboards.yaml
    #   with_items: 
    #     - "{{ target_dashboard_ids }}"
    #   loop_control: 
    #     loop_var: dashboard_id

    - name: get all teams
      include_tasks: tasks/get_all_teams.yaml
    # output -> teams_output

    # - name: Update each team specified
    #   include_tasks: tasks/update_teams.yaml
    #   with_items: 
    #     - "{{ target_team_names }}"
    #   loop_control: 
    #     loop_var: current_team_name
