---
# vars file for SysdigTeam
sysdig_api_endpoint: https://app.sysdigcloud.com
sysdig_token: "{{ lookup('env', 'SYSDIG_TOKEN') }}"

sysdig_team_sa:
  name: "platformservicesteam@gov.bc.ca"
  role: "ROLE_TEAM_STANDARD"

team:
  description: The Sysdig Team for testing
  users:
    - name: billy.li.901@gmail.com
      role: ROLE_TEAM_READ
    - name: better.call@realtorbilly.ca
      role: ROLE_TEAM_READ
    - name: billy.li@gov.bc.ca
      role: ROLE_TEAM_EDIT

# Available Roles Mapping:
# ROLE_TEAM_MANAGER - Removed!
# ROLE_TEAM_EDIT
# ROLE_TEAM_STANDARD
# ROLE_TEAM_READ
